### ISSUE TITLE
Empty scene?

### ISSUE THREAD

**Issue by anderslanglands** [mmikk/hextile-demo#1]
Hi there, and thanks for this repo! Just tried building it in vs2019 and if I run the generated hextile-demo.exe then I get a window but no geometry (and hence no hex tiling) just sky.

**Comment by mmikk** [comment]
Thank you for letting me know! 
I build it in vs2019 myself also and I have received confirmation from others that it is working for them so there must some lingering issue that only impacts under some specific circumstances that hopefully we can figure out.

Can you tell me if you see the subfolder meshes/ as well as the 4 obj files in the folder? You’ll notice they are there in the repo. Assuming they are there can you set a breakpoint in scenegraph.cpp where the 4 calls to ReadObj() are made and see if the files appear to import? Is res true after the 4 calls have been made?

**Comment by anderslanglands** [comment]
Thanks! The issue was that I was just double-clicking the release binary
from x64/Release. Launching it from the terminal in the root of the project
(so that meshes is under the current working directory) fixed it. Thanks
for your fast reply.
